customhost = "database-2.cynmyqinu1ip.us-east-2.rds.amazonaws.com"
customuser = "admin"
custompass = "mypassword"
customdb = "familydetails"
custombucket = "addingfamilydetails"
customregion = "us-east-2"
